ALTER SESSION SET "_oracle_script" = TRUE;

create tablespace TS_VDA
    datafile 'D:\db\TS_VDA.dbf'
    size 7M
    autoextend on next 5M
    maxsize 30M
    extent management local;

create temporary tablespace TS_VDA_TEMP
    tempfile 'D:\db\TS_VDA_TEMP.dbf'
    size 5M
    autoextend on next 3M
    maxsize 20M
    extent management local;
    
SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES;

CREATE ROLE RL_VDACORE;

GRANT CREATE SESSION,
	  CREATE VIEW,
	  CREATE PROCEDURE,
	  CREATE TABLE TO RL_VDACORE;
	 
SELECT * FROM DBA_ROLES WHERE ROLE = 'RL_VDACORE';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_VDACORE';

CREATE PROFILE PF_VDACORE LIMIT
	PASSWORD_LIFE_TIME 180
	SESSIONS_PER_USER 3
	FAILED_LOGIN_ATTEMPTS 7
	PASSWORD_LOCK_TIME 1
	PASSWORD_REUSE_TIME 10
	PASSWORD_GRACE_TIME DEFAULT
	CONNECT_TIME 180
	IDLE_TIME 30;
	
SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_VDACORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

CREATE USER	VDACORE IDENTIFIED BY 12345
	DEFAULT TABLESPACE TS_VDA QUOTA UNLIMITED ON TS_VDA
	TEMPORARY TABLESPACE TS_VDA_TEMP
	PROFILE PF_VDACORE
	ACCOUNT UNLOCK
	PASSWORD EXPIRE;
	
GRANT RL_VDACORE TO VDACORE;

CREATE USER	VDACORE1 IDENTIFIED BY 12345
	DEFAULT TABLESPACE TS_VDA QUOTA UNLIMITED ON TS_VDA
	TEMPORARY TABLESPACE TS_VDA_TEMP
	PROFILE PF_VDACORE
	ACCOUNT UNLOCK
	PASSWORD EXPIRE;

GRANT RL_VDACORE TO VDACORE1;

ALTER USER VDACORE QUOTA 2M on TS_VDA;

ALTER tablespace TS_VDA OFFLINE;

CREATE PROFILE PF_VDAPDB LIMIT
	PASSWORD_LIFE_TIME 180
	SESSIONS_PER_USER 3
	FAILED_LOGIN_ATTEMPTS 7
	PASSWORD_LOCK_TIME 1
	PASSWORD_REUSE_TIME 10
	PASSWORD_GRACE_TIME DEFAULT
	CONNECT_TIME 180
	IDLE_TIME 30;

SELECT * FROM v$pdbs; --NOT IN PDB
