ALTER SESSION SET "_oracle_script" = TRUE; --SYSTEM

SELECT * FROM v$pdbs; --NOT IN PDB

create tablespace TS_Lab3_VDA
    datafile 'D:\db\TS_Lab3_VDA.dbf'
    size 7M
    autoextend on next 5M
    maxsize 30M
    extent management local; -- SYSTEM
   
create temporary tablespace TS_Lab3_VDA_TEMP
    tempfile 'D:\db\TS_Lab3_VDA_TEMP.dbf'
    size 5M
    autoextend on next 3M
    maxsize 20M
    extent management local; -- SYSTEM
    
CREATE ROLE RL_VDAPDB; -- SYSTEM

GRANT CREATE SESSION,
	  CREATE VIEW,
	  CREATE PROCEDURE,
	  CREATE TABLE TO RL_VDAPDB; -- SYSTEM

/*CREATE PROFILE PF_VDAPDB LIMIT
	PASSWORD_LIFE_TIME 180
	SESSIONS_PER_USER 3
	FAILED_LOGIN_ATTEMPTS 7
	PASSWORD_LOCK_TIME 1
	PASSWORD_REUSE_TIME 10
	PASSWORD_GRACE_TIME DEFAULT
	CONNECT_TIME 180
	IDLE_TIME 30;*/

CREATE USER	U1_VDA_PDB IDENTIFIED BY 12345
	DEFAULT TABLESPACE TS_Lab3_VDA QUOTA UNLIMITED ON TS_Lab3_VDA
	TEMPORARY TABLESPACE TS_Lab3_VDA_TEMP
	PROFILE PF_VDAPDB
	ACCOUNT UNLOCK
	PASSWORD EXPIRE; -- SYSTEM

GRANT RL_VDAPDB TO U1_VDA_PDB; -- SYSTEM

CREATE TABLE VDA_table -- U1_VDA_PDB
(
	record_id number(3) PRIMARY KEY,
	record_name varchar2(20)
);

INSERT INTO VDA_TABLE VALUES(2, 'Alex');
INSERT INTO VDA_TABLE VALUES(3, 'John');
INSERT INTO VDA_TABLE VALUES(1, 'Dmitry');

SELECT * FROM VDA_TABLE; -- U1_VDA_PDB

-- VDA_PDB_ADMIN
SELECT * FROM DBA_TABLESPACES;
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES;

GRANT SELECT ANY dictionary TO U1_VDA_PDB;

SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_USERS;

-- SYSTEM orcl
CREATE USER	C##VDA IDENTIFIED BY 12345 CONTAINER = ALL;

GRANT CREATE SESSION, 
      CREATE TABLE TO C##VDA;

     
-- VDA_PDB -- ORLC C##VDA     
ALTER USER C##VDA QUOTA 2M on TS_VDA;
     
CREATE TABLE COMMON_VDA_TABLE
(
	record_id NUMBER(3) PRIMARY KEY,
	record_name varchar2(50)
);

INSERT INTO COMMON_VDA_TABLE values(1, 'Dmitry');
INSERT INTO COMMON_VDA_TABLE values(2, 'Alex'); -- FOR VDA_PDB

SELECT * FROM COMMON_VDA_TABLE;

alter user C##VDA quota unlimited on users;

SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME LIKE '%TABLE%';

SELECT * FROM ALL_OBJECTS WHERE OWNER LIKE '%U1_VDA_PDB%';

SELECT * FROM dba_users;
